Repository Pigrabbit/drive-thru-service, pull requests merged in 2020-09, with the labels that each got.

#11 Feature/login api
  .prettierrc
  server/app.js
  server/controller/auth-controller.js
  server/controller/store-controller.js
  server/package-lock.json
  server/package.json
  server/routes/api-router.js
  server/routes/auth-router.js
  server/utils/auth.js
Labels: Backend, Feature

#12 Config: Local Database 설정 추가
  .gitignore
  .prettierrc
  server/Dockerfile
  server/config/utf8mb4.cnf
  server/docker-compose.yml
  server/sql-scripts/create-tables.sql
Labels: Backend, Devops

#14 Feature/server/cart api
  server/__tests__/repository/store-repository.spec.js
  server/app.js
  server/controller/cart-controller.js
  server/controller/store-controller.js
  server/http/cart.http
  server/http/store.http
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/repository/cart-repository.js
  server/repository/store-repository.js
  server/routes/api-router.js
  server/routes/cart-router.js
  server/routes/store-router.js
  server/service/cart-service.js
  server/service/store-service.js
  server/sql-scripts/create-tables.sql
  server/utils/mockData.js
  server/utils/mysql.js
Labels: Backend, Feature

#15 Feature/client/main page
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/img/category/Asian.jpg
  client/public/img/category/Dessert.jpg
  client/public/img/category/Fastfood.jpg
  client/public/img/icons/account.svg
  client/public/img/icons/arrow_left.svg
  client/public/img/icons/arrow_right.svg
  client/public/img/icons/help.svg
  client/public/img/icons/history.svg
  client/public/img/icons/order.svg
  client/public/img/icons/settings.svg
  client/public/img/store/bhc.jpg
  client/public/img/store/starbucks.jpg
  client/public/img/store/tteokbokki.jpg
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.tsx
  client/src/components/Card.tsx
  client/src/components/CardSection.tsx
  client/src/components/NavItem.tsx
  client/src/components/NavList.tsx
  client/src/components/Sidebar.tsx
  client/src/components/UserPanel.tsx
  client/src/index.css
  client/src/index.tsx
  client/src/pages/MainPage.tsx
  client/src/react-app-env.d.ts
  client/src/setupTests.ts
  client/src/utils/constants.ts
  client/src/utils/style.ts
  client/tsconfig.json
Labels: Feature, Frontend

#16 Feature/client/carousel
  client/src/components/Card.tsx
  client/src/components/CardSection.tsx
  client/src/components/Carousel.tsx
  client/src/components/NavItem.tsx
  client/src/pages/MainPage.tsx
  client/src/utils/constants.ts
  client/tsconfig.json
Labels: Feature, Frontend

#19 Refactor/client/redux
  client/package-lock.json
  client/package.json
  client/src/components/Modal.tsx
  client/src/components/ProductList.tsx
  client/src/index.tsx
  client/src/store/index.ts
  client/src/store/modal/actions.ts
  client/src/store/modal/reducer.ts
  client/src/store/modal/types.ts
Labels: Frontend, Refactoring

#20 Feature/client/cart panel
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/components/CartPanel.tsx
  client/src/components/CartProductItem.tsx
  client/src/components/Modal.tsx
  client/src/components/NavList.tsx
  client/src/components/ProductList.tsx
  client/src/components/Receipt.tsx
  client/src/index.tsx
  client/src/pages/StorePage.tsx
  client/src/store/cart/actions.ts
  client/src/store/cart/reducer.ts
  client/src/store/cart/types.ts
  client/src/store/index.ts
  client/src/store/modal/reducer.ts
  client/src/utils/constants.ts
  client/src/utils/style.ts
  server/controller/cart-controller.js
  server/http/cart.http
Labels: Feature, Frontend

#21 Config/serve build
  .github/workflows/delivery.yml
  .gitignore
  build.sh
  server/app.js
Labels: Config, Devops
